name: discordNotify
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest commit diff
        id: diff
        run: |
          echo "DIFF<<EOF" >> $GITHUB_ENV
          git diff -U0 HEAD~1 HEAD | head -c 1800 >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Discord notification
        uses: tsickert/discord-webhook@v5
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            🚀 **New commit pushed!**
            **Repo:** ${{ github.repository }}
            **Author:** ${{ github.actor }}
            **Message:** ${{ github.event.head_commit.message }}

            ```diff
            ${{ env.DIFF }}
            ```
