name: Notify Discord on Push

on:
  push:
    branches: [ main ]  # change to 'master' if that's your branch name

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 New update pushed to GitHub!"
